app = "lineageos-nibbler"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
REDIS_HOST = "lineageos-redis.internal"
REDIS_PORT = 6379
REDIS_DB   = 0
PYTHONUNBUFFERED = "true"
ENABLE_TWITTER = 1
